[program:hndr]
command=/opt/hndr/bin/suricata -c /opt/hndr/suricata/suricata.yaml -i wlo1 -vv
file=/run/supervisord.sock
chmod=0700
autostart=true
autorestart=true
stderr_logfile=/var/log/suricata/suricata.log
stdout_logfile=/var/log/suricata/suricata.log
