[program:hndr]
command=/opt/hndr/bin/suricata -c /opt/hndr/var/lib/suricata/suricata.yaml --af-packet -vv
file=/run/supervisord.sock
chmod=0700
autostart=true
autorestart=true
stderr_logfile=/var/log/suricata/suricata.log
stdout_logfile=/var/log/suricata/suricata.log
