[program:updater]
command=/opt/updater/bin/updater --config=/opt/updater/config/updater-config.json
autostart=true
autorestart=true
stderr_logfile=/var/log/updater/updater.log
stdout_logfile=/var/log/updater/updater.log
