#!/bin/bash
set -e

# Configuration
TARBALL_PKG="sensor-provision.tar.gz"
SENSOR_IMAGE="sensor:latest"
LOG_DIR="./test_logs"
API_URL="http://localhost:8080"  # Adjust to match nginx or api server port

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Function to print status
print_status() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}SUCCESS: $2${NC}"
    else
        echo -e "${RED}FAILURE: $2${NC}"
        exit 1
    fi
}

# Validate API connectivity
echo "Validating API connectivity..."
if curl -s -k "$API_URL" > /dev/null; then
    print_status $? "API connectivity validated successfully"
else
    print_status $? "Error: API connectivity failed"
    exit 1
fi

# Clean up previous runs
sudo docker rm -f sensor || true
rm -rf "$LOG_DIR" "$TARBALL_PKG"
mkdir -p "$LOG_DIR" "$LOG_DIR/suricata" "$LOG_DIR/updater"

echo "Provisioning tenant and sensor"
provisioner -config=./config/provision-dev-config.json -db=../config/db_dev_config.json -op provision-tenant -tenant-name "tenant1"
provisioner -config=./config/provision-dev-config.json -db=../config/db_dev_config.json -op provision-sensor -tenant-name "tenant1" --device-name "Device 1" -minio=../config/minio_config.json

# Build and upload provisioner and sensor tarball
echo "Building and uploading provisioner and sensor packages"
./deploy.sh provisioner ../config/minio_config.json
./deploy.sh sensor ../config/minio_config.json 1

# pick up sensor package from minio generated by provisioning step above
mc cp myminio/sensor/1/$TARBALL_PKG .

# Build and start sensor container
echo "Building and starting sensor container..."
sudo docker build -f Dockerfile.sensor -t "$SENSOR_IMAGE" .
sudo docker run --name sensor \
  -v "$(pwd)/test_logs/suricata:/var/log/suricata" \
  -v "$(pwd)/test_logs/updater:/var/log/updater" \
  --network host \
  -d "$SENSOR_IMAGE"

# Wait for sensor to stabilize
echo "Waiting for sensor to stabilize..."
sleep 20

# Validate sensor logs
echo "Validating sensor logs..."
sudo docker logs sensor > "$LOG_DIR/sensor.log"
if grep -q "Sensor initialization complete" "$LOG_DIR/sensor.log" &&
   grep -q "hndr entered RUNNING state" "$LOG_DIR/sensor.log" &&
   grep -q "updater entered RUNNING state" "$LOG_DIR/sensor.log"; then
    print_status $? "Sensor logs validated successfully"
else
    print_status $? "Error: Sensor logs validation failed"
    cat "$LOG_DIR/sensor.log"
    exit 1
fi

# Validate suricata logs
echo "Validating suricata logs..."
if [ -f "$LOG_DIR/suricata/suricata.log" ] &&
   grep -q "Hello World" "$LOG_DIR/suricata/suricata.log"; then
    print_status $? "Suricata logs validated successfully"
else
    print_status $? "Error: Suricata logs validation failed"
    ls -l "$LOG_DIR"
    exit 1
fi

# Validate updater logs
echo "Validating updater logs..."
if [ -f "$LOG_DIR/updater/updater.log" ] &&
   grep -q "Status update sent successfully" "$LOG_DIR/updater/updater.log"; then
    print_status $? "Updater logs validated successfully"
else
    print_status $? "Error: Updater logs validation failed"
    ls -l "$LOG_DIR"
    cat "$LOG_DIR/updater.log" || true
    exit 1
fi


# Clean up
echo "Cleaning up..."
sudo docker rm -f sensor

echo "All tests passed successfully!"
