#!/bin/bash
#
# Copyright (c) 2025 SecurITe
# All rights reserved.
#
# This source code is the property of SecurITe.
# Unauthorized copying, modification, or distribution of this file,
# via any medium is strictly prohibited unless explicitly authorized
# by SecurITe.
#
# This software is proprietary and confidential.
set -e

# Defaults for optional behavior
# keep sensor and elastic containers up for debugging
KEEP_SENSOR=false
KEEP_ES=false

# Cleanup function to remove containers and temporary files
cleanup() {
    echo "Performing cleanup..."
    if [[ "${KEEP_SENSOR}" != "true" ]]; then
        sudo docker rm -f sensor 2>/dev/null || true
    else
        echo "Keeping container 'sensor' running as requested."
    fi
    if [[ "${KEEP_ES}" != "true" ]]; then
        sudo docker rm -f es01 2>/dev/null || true
    else
        echo "Keeping container 'es01' running as requested."
    fi
    rm -rf "$LOG_DIR" "$TARBALL_PKG" "$SENSOR_PKG" "$PROVISIONER_PKG" elastic.pem 2>/dev/null || true
    echo "Cleanup completed."
}

# Set trap to call cleanup on script exit or error
trap cleanup EXIT ERR SIGINT SIGTERM

# Print usage/help
usage() {
    echo "Usage: $0 [options] [tenant-name] [device-name] [top-level-cfg-dir]"
    echo "  Test deployment for specific tenant and device"
    echo "  tenant-name (default tenant1)"
    echo "  device-name (default dev1)"
    echo "  cfg-dir (default config)"
    echo ""
    echo "Options:"
    echo "  -k, --keep         Keep the 'sensor' container running after tests"
    echo "      --keep-all     Keep both 'sensor' and 'es01' containers"
    echo "  -h, --help         Show this help"
    exit 1
}

# Parse leading options
OPTS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -k|--keep)
      KEEP_SENSOR=true; shift ;;
    --keep-all)
      KEEP_SENSOR=true; KEEP_ES=true; shift ;;
    -h|--help)
      usage ;;
    --) shift; break ;;
    -*)
      echo "Unknown option: $1"; usage ;;
    *)
      OPTS+=("$1"); shift ;;
  esac
done
set -- "${OPTS[@]}" "$@"

[[ $# -lt 3 ]] && usage
TENANT_NAME=${1:-"tenant1"}
DEVICE_NAME=${2:-"dev1"}
CFG_DIR=${3:-"config"}

# Configuration
TARBALL_PKG="sensor-provision.tar.gz"
SENSOR_IMAGE="sensor:latest"
LOG_DIR="./test_logs/securite"
API_URL="http://localhost:8080"  # Adjust to match nginx or api server port
SENSOR_PKG="sensor-provision.tar.gz"
PROVISIONER_PKG="package.tar.gz"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Function to print status
print_status() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}SUCCESS: $2${NC}"
    else
        echo -e "${RED}FAILURE: $2${NC}"
        exit 1
    fi
}

# Validate API connectivity
echo "Validating API connectivity..."
if curl -s -k "$API_URL" > /dev/null; then
    print_status $? "API connectivity validated successfully"
else
    print_status $? "Error: API connectivity failed"
    exit 1
fi

# Clean up previous runs
sudo docker rm -f sensor || true
rm -rf "$LOG_DIR" "$TARBALL_PKG"
mkdir -p "$LOG_DIR" "$LOG_DIR/suricata" "$LOG_DIR/updater" "$LOG_DIR/certs"

echo "Provisioning tenant and sensor"
OUTPUT=$(provisioner -config=$CFG_DIR/provisioner/provision-dev-config.json -db=$CFG_DIR/db_dev.json -op provision-tenant -tenant-name "$TENANT_NAME")
ODEVID=$(provisioner -config=$CFG_DIR/provisioner/provision-dev-config.json -db=$CFG_DIR/db_dev.json -op provision-sensor -tenant-name "$TENANT_NAME" --device-name "$DEVICE_NAME" -minio=$CFG_DIR/minio.json)

echo "$OUTPUT"
TENANT_ID=$(echo "$OUTPUT" | grep -oE 'ID=[0-9]+' | cut -d= -f2)
echo "$ODEVID"
DEVICE_ID=$(echo "$ODEVID" | grep -oE 'device=[a-zA-Z0-9-]+' | cut -d= -f2)

TEST_FILE_RULES=hndr-rules-tid_$TENANT_ID-r1.2.3.tar.gz
cp  ../minio/hndr-rules-r1.2.3.tar.gz /tmp/$TEST_FILE_RULES

# echo "Uploading images to minio"
objupdater -type software -dbconfig $CFG_DIR/db_dev.json -minioconfig $CFG_DIR/minio.json -file ../minio/hndr-sw-v1.2.3.tar.gz
objupdater -type rules -dbconfig $CFG_DIR/db_dev.json -minioconfig $CFG_DIR/minio.json -file /tmp/$TEST_FILE_RULES -tenantid $TENANT_ID
objupdater -type threatintel -dbconfig $CFG_DIR/db_dev.json -minioconfig $CFG_DIR/minio.json -file ../minio/threatintel-2025.04.10.1523.tar.gz

# Build and upload provisioner and sensor tarball
echo "Building sensor packages"
create-tarball.sh sensor $CFG_DIR $TENANT_ID $DEVICE_ID

# pick up sensor package from minio generated by provisioning step above
curl -k https://localhost/v1/$TENANT_ID/$DEVICE_ID/sensor-provision.tar.gz -o sensor-provision.tar.gz

# may need to increase this limit for elastic container to come up
sudo sysctl -w vm.max_map_count=262144

elastic_key.sh

# Build and start sensor container
echo "Building and starting sensor container..."
sudo docker build --network host -f Dockerfile.sensor -t "$SENSOR_IMAGE" .
sudo docker run --name sensor \
  -v "$(pwd)/test_logs/securite/suricata:/var/log/securite/suricata" \
  -v "$(pwd)/test_logs/securite/updater:/var/log/securite/updater" \
  --network host \
  -d "$SENSOR_IMAGE"

# Wait for sensor to stabilize
echo "Waiting for sensor to stabilize..."
sleep 120

# Validate sensor logs
echo "Validating sensor logs..."
sudo docker logs sensor > "$LOG_DIR/sensor.log"
if grep -q "Sensor initialization complete" "$LOG_DIR/sensor.log" &&
   grep -q "filebeat entered RUNNING state" "$LOG_DIR/sensor.log" &&
   grep -q "hndr entered RUNNING state" "$LOG_DIR/sensor.log" &&
   grep -q "updater entered RUNNING state" "$LOG_DIR/sensor.log"; then
    print_status $? "Sensor logs validated successfully"
else
    print_status $? "Error: Sensor logs validation failed"
    cat "$LOG_DIR/sensor.log"
    exit 1
fi

# Validate suricata logs
echo "Validating suricata logs..."
if [ -f "$LOG_DIR/suricata/suricata.log" ] &&
   grep -q "Hello World" "$LOG_DIR/suricata/suricata.log"; then
    print_status $? "Suricata logs validated successfully"
else
    print_status $? "Error: Suricata logs validation failed"
    ls -l "$LOG_DIR"
    exit 1
fi

# Validate updater logs
echo "Validating updater logs..."
if [ -f "$LOG_DIR/updater/updater.log" ] &&
   grep -q "Status update sent successfully" "$LOG_DIR/updater/updater.log"; then
    print_status $? "Updater logs validated successfully"
else
    print_status $? "Error: Updater logs validation failed"
    ls -l "$LOG_DIR"
    cat "$LOG_DIR/updater.log" || true
    exit 1
fi

echo "All tests passed successfully!"

# If we kept the sensor up, print quick-ops hints
if [[ "${KEEP_SENSOR}" == "true" ]]; then
  echo ""
  echo "------------------------------------------------------------------------"
  echo "The 'sensor' container is still running."
  echo "------------------------------------------------------------------------"
fi
